---
- name: Restart MongoDB
  ansible.builtin.command: "docker restart {{ item }}"
  with_items:
    - "{{ mongodb_name }}"

- name: Remove MongoDB
  ansible.builtin.command: "docker stop {{ item }} && docker rm {{ item }}"
  register: results
  with_items:
    - "{{ mongodb_name }}"
  failed_when: >-
    results is failed and
    "No such container" not in results.stderr | default(false)
